global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ledger-link'
    static_configs:
      - targets: ['ledger-link:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scheme: http
