version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ledger_link_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ledger_link
      MYSQL_USER: ledger_user
      MYSQL_PASSWORD: ledger_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=rootpass",
        ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  mysql_data:
